### ISSUE TITLE
Reloading multiple screens is not supported

### ISSUE THREAD

**Issue by saurabhdaware** [abelljs/abell#104]
**Describe the bug**

If we open localhost in multiple tabs, and start the dev server. Refresh is triggered only on one page.

**To Reproduce**

1. Start the dev server with `npm run dev`
2. Open localhost link browser
3. Open Network link in other tab or different device.
4. Make changes in any file and save.

Reload will be triggered only in one of them.

**Expected behavior**

Reload should trigger everywhere.

**Comment by saideepesh000** [comment]
Ya, interestingly it is refreshing/updating/loading the latest reloaded/updated page 😂😂. Let me check for React too, I've seen this kind of issue for the first time.

**Comment by saideepesh000** [comment]
Hey @saurabhdaware, while I am trying to set up the abelljs for contributing, after starting "abell serve", I am seeing this, is this an error or something else. 
![Screenshot (291)](https://user-images.githubusercontent.com/43727167/103153240-2f1cc780-47b5-11eb-992a-fd09dd480dce.png)

**Comment by saurabhdaware** [comment]
yup this is expected. It is main example from examples/main directory

**Comment by saideepesh000** [comment]
> 
> 
> yup this is expected. It is main example from examples/main directory

U mean it is an error or an expected/desired output, I didn't get it.

**Comment by saurabhdaware** [comment]
> > yup this is expected. It is main example from examples/main directory
> 
> U mean it is an error or an expected/desired output, I didn't get it.

it is expected

**Comment by saurabhdaware** [comment]
Resolved in 47a19b727494b2af89baddf6282c5eb32970b63c
