### ISSUE TITLE
Markdown files being parsed as Abell content

### ISSUE THREAD

**Issue by harshhhdev** [abelljs/abell#125]
# Describe the bug

When I use the standard Abell syntax of `${{ variable }}` inside of a markdown file, it gets parsed as regular Abell code, and causes an error.

# To Reproduce

 - Create a new blog
 - Add `${{ text}}` inside of the markdown file.

# Expected behaviour

Don't parse the content inside of the markdown files with Abell syntax.

# Screenshots

![image](https://user-images.githubusercontent.com/69592270/127569758-b94f86a0-7f7c-4e1e-8cab-f2886fcd414c.png)

![image](https://user-images.githubusercontent.com/69592270/127569781-39e361df-abcd-4f12-b228-72b05414c31e.png)

# Specs:

- Abell Version: v0.10.3
- Node Version: v16.5.0
- Operating System: Arch Linux

**Comment by harshhhdev** [comment]
BTW, I'm aware I can escape the curly brackets by adding a "\" infront, but the main issue I wanted to point out here was markdown files being processed as Abell content.

**Comment by saurabhdaware** [comment]
oh yup it was intentional earlier to pass some extra information to markdown files. Might remove this in future versions. 

Can't think of any other way that will allow markdown files to be dynamic and still not cause this issue 🤔

**Comment by saurabhdaware** [comment]
Leaving this open for now. Can resolve it when I add some alternative

**Comment by saurabhdaware** [comment]
They will not be parsed in v1. Closing this since I am mostly maintaining and focussing on v1 right now. Will re-open if I plan to add some type of parsing in v1.
