### ISSUE TITLE
Error handling to avoid exiting the dev-server, if error occurs.

### ISSUE THREAD

**Issue by saurabhdaware** [abelljs/abell#16]
Currently, if you're working in dev-server and an error occurs, let's say you write a variable that is undefined, In this case the dev-server is closed after throwing the error.

## How to reproduce
- `abell serve` after [setting up this repo locally](https://github.com/abelljs/abell/blob/main/CONTRIBUTING.md).
- In `demo/index.abell`, write a variable that is not defined anywhere.
- This will throw the error in terminal and will close the dev-server.

## How it should work
- It should throw error but should not exit the dev-server.

## Code help
[`serve`](https://github.com/abelljs/abell/blob/main/src/commands/serve.js) function handles the dev-server, if we add try-catch for error handling there, it should avoid exiting the server I believe.

**Comment by Pika1998** [comment]
I think this issue is solved correct?

**Comment by saurabhdaware** [comment]
It is only solved for the error when variable is undefined, Are there any other errors that can occur while working with Abell?

**Comment by Pika1998** [comment]
If i try something like this, the web server throws an error, but the console shows nothing
```js
{{
  const abc = require('./abac.json');
}}
{{ abc }}
```
Here there is no such file as **abac.json**

**Comment by Pika1998** [comment]
> Currently, if you're working in dev-server and an error occurs, let's say you write a variable that is undefined, In this case the dev-server is closed after throwing the error.
> 
> ## How to reproduce
> * `npm run dev:serve` after [setting up this repo locally](https://github.com/abelljs/abell#3-contributing-to-abell).
> * In `demo/index.abell`, write a variable that is not defined anywhere.
> * This will throw the error in terminal and will close the dev-server.
> 
> ## How it should work
> * It should throw error but should not exit the dev-server.
> 
> ## Code help
> [`serve`](https://github.com/abelljs/abell/blob/master/src/action.js#L107) function handles the dev-server, if we add try-catch for error handling there, it should avoid exiting the server I believe.

Here the  **serve** link is invalid can you change that?

**Comment by saurabhdaware** [comment]
Fixed! Thanks

**Comment by saurabhdaware** [comment]
> If i try something like this, the web server throws an error, but the console shows nothing
> 
> ```js
> {{
>   const abc = require('./abac.json');
> }}
> {{ abc }}
> ```
> 
> Here there is no such file as **abac.json**

Oh yes we need to show proper error here

**Comment by saurabhdaware** [comment]
Fixed in Abell v0.4
