### ISSUE TITLE
Additional Padding in Algolia Search

### ISSUE THREAD

**Issue by saurabhdaware** [abelljs/abell#169]
**Describe the bug**

Some CSS from Abell must be adding some additional padding to Algolia Search Container

<img width="657" alt="image" src="https://github.com/abelljs/abell/assets/30949385/7ca9538c-e7ee-4d35-9f2c-4d4fc20778e9">

**To Reproduce**

1. Go to https://abelljs.org/docs/getting-started
2. Click Search
3. Type something in search
4. See the padding of the container

**Expected behavior**

There shouldn't be any additional padding apart from what Algolia gives

Example of expected look from Vite docs

<img width="706" alt="image" src="https://github.com/abelljs/abell/assets/30949385/12acec95-a56e-4dfd-b07c-5f6f758e66f3">

**Comment by manancodes** [comment]
I would like to work on this one. Assign this to me.
Commenting here so that nobody else works on this.

**Comment by saurabhdaware** [comment]
sure @manancodes go ahead 🥳
