### ISSUE TITLE
Better way to write components/partials

### ISSUE THREAD

**Issue by saurabhdaware** [abelljs/abell#27]
**Is your feature request related to a problem? Please describe.**

Currently, components are just JS files that return string of html css javascript, if a component needs to return javascript, the code loooks super uglyyy.

**Describe the solution you'd like**
A component similar to Vue component but rendered with Abell instead

**Additional context**
Idea:
```jsx
// Footer.abellc
<AbellComponent injections>
<template>
  <footer>My Footer! {{ injections.footerLinks }} <span id="year"></span></footer>
</template>
<style>
  footer { padding: 10px; }
</style>
<script>
  document.querySelector('#year').innerText = new Date().getFullYear();
</script>
</AbellComponent>
```

**Comment by saurabhdaware** [comment]
We can write `inlined` attribute that makes the script inlined, or else it will create separate bundle of these scripts

```html
<AbellComponent injections={footerLinks}>
<template>
  <footer>My Footer! {{ footerLinks }} <span id="year"></span></footer>
</template>
<style>
  footer { padding: 10px; }
</style>
<script inlined>
  document.querySelector('#year').innerText = new Date().getFullYear();
</script>
</AbellComponent>
```

**Comment by Judionit** [comment]
Hey,
This project is great, but I want to give a suggestion in this, what about something like react component?

**Comment by saurabhdaware** [comment]
Thank you @Judionit! That will work great with the HTML content but any idea how we can have CSS and JS? I kind of like the idea of Vue to be able to have everything related to the component in a single file. I felt like this way it will also look close to the `.html` files so there will be lesser things to learn. 

Let me know your thoughts :D

**Comment by Judionit** [comment]
Oh yeah, making html css and js in one file is an advantage, that why I love vue too

if you need some help let me know 🙂

**Comment by Judionit** [comment]
But the idea with react component is, we can have the js and html in one file and css on other file

**Comment by saurabhdaware** [comment]
yup, that would be cool too but then the issue is the way we handle client-side js is very different from React. React has state management and all the additional things for client-side JavaScript whereas Abell is a static-site-generator, so the client-side javascript is not really the focus. The way we handle JS is same as the way JS is handled in the vanilla HTML file.

So the only need of component here is to group together related code.

**Comment by saurabhdaware** [comment]
> if you need some help let me know slightly_smiling_face

Yes yes if any help is needed will definitely let you know, currently I will leave this issue open and see what others think since this will be very important addition to Abell. 

Meanwhile, you can check out and play around Abell and let us know if you think something can be better or if there's any bug maybe you can try to solve it if you're interested :D

**Comment by saurabhdaware** [comment]
In addition to syntax I've mentioned earlier, maybe we can support two (optional) script tags:
```html
<AbellComponent injections={footerLinks}>
<template>
  <footer>My Footer! {{ footerLinks }} <span id="year"></span></footer>
</template>
<style>
  footer { padding: 10px; }
</style>
<script inlined>
  // This will be added inlined inside the HTML
  document.querySelector('#year').innerText = new Date().getFullYear();
</script>
<script>
  // This will be bundled into separate file.
  // *Imaging a really long JS code here that is not needed initially*
</script>
</AbellComponent>
```
+ Same with CSS

This way we can have critical and non-critical styles and scripts in the same file.

**Comment by Judionit** [comment]
maybe you can use only one script tags but separate the inlined and others script inside this one script tags ?
same for css

**Comment by saurabhdaware** [comment]
```html
<script>
  <inlined>
   // ..critical scripts
  </inlined>
 // .. remaining
</script>
```
Like this? Yeah this sounds like a nice idea too

**Comment by Judionit** [comment]
yes, like that so we don't have to deal with 2 script tag

**Comment by Pika1998** [comment]
This is interesting, I loved the idea of bundling CSS and long js files together,  but I feel that having a separate viewer for both would be good, like for example ... some VSCode magic, which displays CSS in a separate window and JS in a separate window, but they are actually bundled in the same file.

**Comment by saurabhdaware** [comment]
> This is interesting, I loved the idea of bundling CSS and long js files together, but I feel that having a separate viewer for both would be good, like for example ... some VSCode magic, which displays CSS in a separate window and JS in a separate window, but they are actually bundled in the same file.

Not sure if I understand what you mean, but in VSCode you can open same file side-by-side.

**Comment by saurabhdaware** [comment]
https://abelljs.org/syntax-guide#abell-components is deployed 🎉 Thank you @judicaelandria and @Pika1998 for your views :D

**Comment by judicaelandria** [comment]
Greeeaat! 🔥
My pleasure
