### ISSUE TITLE
description issue

### ISSUE THREAD

**Issue by veluvj** [abelljs/abell#29]
I created a new folder with  description at **meta.json** but it not changes in main page

`{
    "title": "array.Push()",
    "description": "Javascript array.push() method."
  }
`

look at tha description in **main page**  

![Screenshot from 2020-06-18 10-31-52](https://user-images.githubusercontent.com/38492388/84980370-8891a300-b14f-11ea-9abe-94d48381df05.png)

**Comment by saurabhdaware** [comment]
Did it change after restarting the dev server?

**Comment by veluvj** [comment]
No, still the same description.

**Comment by saurabhdaware** [comment]
oh ok I'll check it out, thanks!

**Comment by saurabhdaware** [comment]
I created a new project and it is working for me, Can you try updating Abell (`npm install --save-dev abell@latest`)?

Also, do you see any message in terminal of dev server?

![screenshot of home page of blog that displays the description from meta.json](https://user-images.githubusercontent.com/30949385/84996110-796c1e80-b16a-11ea-8bbd-3ed71f9cebf8.png)
