### ISSUE TITLE
build and serve error

### ISSUE THREAD

**Issue by Judionit** [abelljs/abell#33]
**Describe the bug**
Hey,
When I run npm run dev:serve or npm run dev:build I always getting this error
![build](https://user-images.githubusercontent.com/46365844/85195163-0e8d2580-b2d9-11ea-80ec-7f278eaebc09.PNG)

![serve](https://user-images.githubusercontent.com/46365844/85195172-151b9d00-b2d9-11ea-85e8-2a556570d2c5.PNG)

**Comment by saurabhdaware** [comment]
Did it happen on the first run? or after changing the content?

**Comment by Judionit** [comment]
happen on the first run

**Comment by saurabhdaware** [comment]
I am not really sure how I can reproduce this issue, if you're interested in solving this bug I can help in debugging what is wrong.

So looking at the log I believe the value of contentTemplate must be `null` for some reason in https://github.com/abelljs/abell/blob/main/src/content-generator.js#L292

In that function maybe you can `console.log(programInfo.contentIndexTempate)` and see if it is null

if it is null, it must be coming from here: https://github.com/abelljs/abell/blob/main/src/content-generator.js#L168

It will throw this error if `theme/[$path]/index.abell` is empty I guess

**Comment by Judionit** [comment]
yeah,  it's null

**Comment by saurabhdaware** [comment]
Maybe we can change this line: https://github.com/abelljs/abell/blob/main/src/content-generator.js#L168 to send '' (empty string) instead of null when the value is an empty string.

Would you be interested in creating a Pull Request?

**Comment by Judionit** [comment]
yeah, of course

**Comment by saurabhdaware** [comment]
Awesome! let me know if you need any help :D

**Comment by Judionit** [comment]
done, sent the pr
