### ISSUE TITLE
End-to-end tests for internal pages of test example

### ISSUE THREAD

**Issue by saurabhdaware** [abelljs/abell#38]
In [cypress/examples](https://github.com/abelljs/abell/tree/main/tests/cypress/examples) you would find example abell projects, they have multiple pages. But if you see [cypress/e2e](https://github.com/abelljs/abell/tree/main/tests/cypress/e2e), we only have tests for index pages of all examples.

We need to write tests for content pages and other pages of the standard example.

**Files to update:** https://github.com/abelljs/abell/blob/main/tests/cypress/e2e/standard.spec.js 

Check out E2E Test section from [Testing Guide](https://github.com/abelljs/abell/tree/main/tests) for details on how to run tests

**Comment by harshilparmar** [comment]
Can I try this?

**Comment by saurabhdaware** [comment]
Yes yes go for it! let me know if you need any help

**Comment by harshilparmar** [comment]
@saurabhdaware Brother I am going through whole abell workflow just for my understanding But I am getting Unexpected end of input.Is there any issue? or I am done something wrong?

**Comment by saurabhdaware** [comment]
Can you share the screenshot of error? Also try updating abell I guess we've fixed this in new version

**Comment by harshilparmar** [comment]
yes !!
![Capture](https://user-images.githubusercontent.com/45915468/86436422-d85f9500-bd1f-11ea-953a-43eb743d7a69.PNG)

**Comment by saurabhdaware** [comment]
Oh I just realized the abell-starter-minima is using 0.3.1 version of abell which had this bug, It is fixed in 0.3.2, you can `npm install --save-dev abell@latest` to get 0.3.2. It should fix the issue.

**Comment by saurabhdaware** [comment]
Fixed it in abell-starter-minima as well, so starting a new project is supposed to fix it as well

**Comment by harshilparmar** [comment]
Brother, I have started this issue, but I got errors for both minimal and standard examples 
![Build Standard template with deep routes and content (examplesminimal) -- should render executed JavaScript even without content -- before each hook (failed)](https://user-images.githubusercontent.com/45915468/86535080-51ffaa80-befb-11ea-9fa5-5848faa568f4.png)
![Build Standard template with deep routes and content (examplesstandard) -- should render executed JavaScript -- before each hook (failed)](https://user-images.githubusercontent.com/45915468/86535111-81aeb280-befb-11ea-99c8-3c7762dbd162.png)

I started the test server in one terminal and e2e test in second.

This is working fine when I make build for both examples manually 

I think there is a problem in build-test-examples file because It is not making build for examples.
Please correct me and guide me. I am doing  testing first time.

**Comment by saurabhdaware** [comment]
Does the server runs correctly when you `npm run test-server`?

**Comment by harshilparmar** [comment]
Yes it's serving correctly,I didn't get any errors.

**Comment by saurabhdaware** [comment]
After running `npm run test-server`, in `tests/cypress/examples/standard` is there `dist` directory?

so npm run test-server, builds all the examples inside `tests/cypress/examples` and serves that directory. Then we navigate to the `standard/dist` to get read the html site

**Comment by harshilparmar** [comment]
Yes, it is running on localhost:5000.

No, there is no dist folder of any examples after running the test-server. That's why I tried to make build manually and that's working fine.

**Comment by saurabhdaware** [comment]
Not really sure what is happening, can you debug the code in [build-test-examples.js](https://github.com/abelljs/abell/blob/main/tests/cypress/scripts/build-test-examples.js) and see what is causing this? It seems to work in my machine and it even works in GitHub Actions so not sure how I can reproduce this.

The build-test-examples is supposed to build the examples and create dist in every examples

**Comment by saurabhdaware** [comment]
Hi, Have you started working on this? I thought of another way to write tests

**Comment by harshilparmar** [comment]
No Brother I haven't  got any solution for that problem ,so I have not started yet.

**Comment by saurabhdaware** [comment]
Cool cool then I'll just setup a new tests and then you can write tests for that

**Comment by saurabhdaware** [comment]
Hey @harshilparmar, So we moved tests from `cypress` to `cheerio` and now it does not require running any server, you can just `npm test` and it will run all the tests including e2e tests. The tests are in examples directory in the respective folders of particular example.


Here's test for index.html of the `examples/main` -> https://github.com/abelljs/abell/blob/main/examples/main/main.spec.js

This way we need to write tests for other files in the `examples/main/dist`.

**Comment by harshilparmar** [comment]
OK, thanks,So I have to right tests for all examples build files right?

**Comment by saurabhdaware** [comment]
Yes it's up to you how many tests you want to write. Majorly we need test for `main/dist/[$path]/index.abell` and `example.abell` in the same directory.

In other examples, you may have to change the `.abell` files a bit to highlight the specific features. For examples, in with-dev-source example, we have to check if it renders the articles properly.

`with-plugins` and `with-async-plugins` will not really need any test since what it does is tested in `main` example and the other things are not testable yet.

**Comment by harshilparmar** [comment]
Bro, build not rendering properly.
![Untitled](https://user-images.githubusercontent.com/45915468/87460252-3054a080-c62a-11ea-9fea-1475812937cf.png)

There is an error regarding `test.mjs`.It is not getting while serve.

**Comment by saurabhdaware** [comment]
Hi it did build properly and what you see on screen is expected.

About the test.mjs error, you can ignore that error it is not related to Abell. I think I might have left link to test.mjs file somewhere in the index.abell. You can remove that line that includes test.mjs if you dont want to see the error.

Everything is working as expected

**Comment by harshilparmar** [comment]
I thought css is not working!!

**Comment by saurabhdaware** [comment]
no it doesn't have css. we only want to test abell functionality so anything that is not covered by abell is not needed in tests

**Comment by saurabhdaware** [comment]
Resolved in #56 Thank you @harshilparmar 🎉
