### ISSUE TITLE
Expose beforeWrite function for plugins

### ISSUE THREAD

**Issue by saurabhdaware** [abelljs/abell#42]
**Is your feature request related to a problem? Please describe.**
There should be some way we can change the content before creating files, this way we can allow plugins that add new variables or content to the .abell files. 

**Describe the solution you'd like**

From plugins we should be able to do
```js
function beforeRender(abellTemplate) {
  // ... operations
  return newAbellTemplate;
}
module.exports = { beforeRender }
```

This function should run before we call `abellRenderer.render` function while turning .abell files to .html 

**Additional context**

## Changes in Code
So this is the code that exposes `afterBuild` function for plugins (the code may move a little up or down if I change file in next commits) https://github.com/abelljs/abell/blob/main/src/commands/build.js#L102-L114

To run that function before the render, we will have to expose the function from https://github.com/abelljs/abell/blob/main/src/utils/build-utils.js#L219 before calling `abellRenderer.render`

## Testing plugins locally

After following [the Local Setup Guide from CONTRIBUTING.md](https://github.com/abelljs/abell/blob/main/CONTRIBUTING.md)

- `cd examples/with-plugin`
- `abell build`

This will run the [plugin example from the example folder](https://github.com/abelljs/abell/tree/main/examples/with-plugin) .
You will have to add a sample `beforeRender` function in plugins/index.js to run beforeRender as well.

**Comment by edemagbenyo** [comment]
I would like to work on this issue.

**Comment by saurabhdaware** [comment]
Hi @edemagbenyo Thank you for showing interest. I am actually working on refactoring the plugins part completely so working on this now may create some major conflicts later. 

The refactor is supposed to be completed by the next week (hopefully) so I think it will be better to work on this after the refactor.

**Comment by edemagbenyo** [comment]
@saurabhdaware I will wait then

**Comment by saurabhdaware** [comment]
Hi @edemagbenyo , you can work on this now just make sure you make a branch out of [next](https://github.com/abelljs/abell/tree/next) which has the new refactored code. It will take some until we make merge it into default branch.

I think we can call the function `beforeWrite` instead of `beforeRender` and call the function from plugin before we write HTML here: 
https://github.com/abelljs/abell/blob/next/src/utils/generate-site.js#L106

[src/utils/general-helpers.js](https://github.com/abelljs/abell/blob/next/src/utils/general-helpers.js) file has beforeBuild and afterBuild execution functions so you can refer to that.

Thank you and let me know if you need any help!

**Comment by saurabhdaware** [comment]
Oh and also let me know if you have any other ideas/suggestions or want to try out a new method. Thank you!

**Comment by saurabhdaware** [comment]
Update: The code is in main branch now

**Comment by saurabhdaware** [comment]
I am working on this. Adding `beforeHTMLWrite` function to plugins

**Comment by saurabhdaware** [comment]
Resolved in https://github.com/abelljs/abell/releases/tag/v0.4.0
