### ISSUE TITLE
Add meta.$readingTime variable in .abell files

### ISSUE THREAD

**Issue by saurabhdaware** [abelljs/abell#43]
It can be a helpful parameter for users to know how long an article can take to read.

This article has formula needed to calculate the reading time: https://marketingland.com/estimated-reading-times-increase-engagement-79830

`generateContent` function in [src/utils/built-utils.js](https://github.com/abelljs/abell/blob/main/src/utils/build-utils.js) deals with the code of adding variables to the .abell files

**Comment by harshilparmar** [comment]
We have to count word of `index.md` file right??

**Comment by saurabhdaware** [comment]
yes

**Comment by harshilparmar** [comment]
My approach is for this is go to build folder and read file for counting words using  `abellConfigs.destinationPath` which gives me path of dist folder. I have tried this is this fine??

**Comment by saurabhdaware** [comment]
dist folder will be empty or will have the old content before performing build and writing files and after build, we won't be able to inject variables into it.

I just realized the way I thought this issue can be solved, it can't be solved that way so it is complicated than I thought.

I had thought of counting words from `importContent` function in https://github.com/abelljs/abell/blob/main/src/utils/build-utils.js#L168 but the issue is, we don't know what `md` files user may put in the path. 

That path is dynamic and decided when the abell renders that file so we can't predict the path already and thus can't count the word.

One way it can be executed is by reading the `index.md` in `getMetaContent` but that way it will possibly read the files twice so that will increase the build time.

One solution would be to read the file size instead of file and depending on the file size, we can predict the number of words in it

**Comment by harshilparmar** [comment]
I have made something like this

 `fs.readFile(
    `${abellConfigs.destinationPath}\\${contentDirectories[1]}\\index.html`,
    'utf-8',
    function (err, data) {
      if (data) {
        let res = data.match(/(?<=\>).+?(?=\<)/g);
        console.log(res.join("").split(" ").length);
      }
    }
  );`
But as you said, we can't inject variable into it right.

**Comment by saurabhdaware** [comment]
I will close this temporary since it is not very important right now, Maybe in future, we can reopen
