### ISSUE TITLE
Idea: Abell renderer for emails

### ISSUE THREAD

**Issue by pantharshit00** [abelljs/abell#58]
**Is your feature request related to a problem? Please describe.**
I think abell would be a very good fit for writing email templates. The syntax is close to html.

**Describe the solution you'd like**
Most like we will need to make some abell components which will mimic the html email mess which are the tables. I can share more ideas about that after we release components.

**Additional context**
(Hm, just dropping an idea right now.)

**Comment by saurabhdaware** [comment]
Yes yes we can do that! I think we can do that directly without making any changes in Abell's code, right?

**Comment by pantharshit00** [comment]
Yes, I will explore this after 0.4 is released 😄

**Comment by judicaelandria** [comment]
Hey @saurabhdaware ,
when 0.4 will be released?

**Comment by saurabhdaware** [comment]
It's almost done, I am working on documentation. Should be up by the next week :D

**Comment by saurabhdaware** [comment]
Just cleaning some issues for Hacktoberfest.

I think we can directly do this using [abell-renderer](https://github.com/abelljs/abell-renderer) so I'll close this for now.
