### ISSUE TITLE
Dev server: listen on next available port if port 5000 is not free

### ISSUE THREAD

**Issue by pantharshit00** [abelljs/abell#61]
**Is your feature request related to a problem? Please describe.**
Pretty self explanatory. Most popular dev server listen on the next avaliable port if the default port is not available. This saves you from finding the process which is consuming that port.

Right now abell just crashes:
![image](https://user-images.githubusercontent.com/22195362/90315621-6f805500-df3a-11ea-8c4c-ca153fd9f10c.png)

**Describe the solution you'd like**
Listen on next available port if port 5000 is occupied. Do not do this if user has specified the port.

**Additional context**
https://github.com/facebook/create-react-app/blob/8e761d19d14f47afdbbcfa6e19ed50c8ea1a63f4/packages/react-dev-utils/WebpackDevServerUtils.js#L448

**Comment by saurabhdaware** [comment]
Yep this is neccessary! Thanks for opening the issue. Keeping this open if someone wants to work on this.

**Comment by pantharshit00** [comment]
I will most likely pick this up. Thanks!
