### ISSUE TITLE
Inline components

### ISSUE THREAD

**Issue by pantharshit00** [abelljs/abell#69]
**Is your feature request related to a problem? Please describe.**
Right now everytime you need to make a new component, you will need to make a new `.abell` file. It works fine for the most part but it is very ideal for quick iteration or if you want to reuse some logic in the same component. You will still need to spill the reused part into its own file which creates file system mes..

**Describe the solution you'd like**
Design Inline components for abell. Right now I don't have a concrete idea in mind as abell files right now are like a single file component. This issue is meant for persisting this idea for the future. 

**Additional context**
I would look into Vue.js as they have kind same concept of a single file component which vue community seems to love. Maybe we don't need this altogether.

**Comment by saurabhdaware** [comment]
Yes, this would be great. I love react for this. With this we can also give out a single code which user can paste and run and it just works. 

#71 will help in this too

**Comment by saurabhdaware** [comment]
I will close this issue as we can discuss/explore it in #71
