### ISSUE TITLE
Add tests for Websocket server

### ISSUE THREAD

**Issue by pantharshit00** [abelljs/abell#72]
https://github.com/abelljs/abell/pull/64 adds tests for the http server used in development but we also have a websocket server

This issue is here to track that part.

**Comment by saurabhdaware** [comment]
We can call fs.writeFile in that file and it should trigger the reloads as well. So I think we can follow something like this.

**Comment by saurabhdaware** [comment]
I am refactoring tests today. Let's move to JEST. I will try to resolve this while refactoring.
