### ISSUE TITLE
Link external scripts and styles in component

### ISSUE THREAD

**Issue by saurabhdaware** [abelljs/abell#89]
```vue
<AbellComponent>

<style href="external.css"></style>
</AbellComponent>
```

Sleepy now so just dropping it here. I will add more info later

**Comment by saurabhdaware** [comment]
Should we use `src` or `href` ?

```vue
<AbellComponent>
<template>
  <div></div>
</template>
<style src="external.css"></style>
<script src="external.js"></script>
</AbellComponent>
```

**Comment by judicaelandria** [comment]
I think src is better than href

**Comment by saurabhdaware** [comment]
Yes src seems good. Before we start working on this, There are some gotchas in this. For example, what if A.abell and B.abell both use C.js file and it is scoped in both the files. Should code in C.js be scoped for A, should it be scoped for B, should it be bundled twice? 

This will be confusing to solve.

**Comment by judicaelandria** [comment]
if two abell file use one javascript file, it's should bundled, but only once
but the other option is good too
if a.abell use is open in the browser it will br scoped in a file and same for be

**Comment by saurabhdaware** [comment]
So for scope, we have to use hash that is separate for each component. `abell-data-xyz` for a.abell and `abell-data-abc` for b.abell.

In styles, we append this hash on selector For example: `nav[abell-data-xyz]`. So it is always limited to one file. If we want to scope style for two components, we will have to generate two different style blocks with different hash appended. 

So it is going to be tricky on implementation side :thinking:

**Comment by judicaelandria** [comment]
big implementation, maybe there is an easy way to do that?
we can ask the member in the discord to see what they think? 😃

**Comment by saurabhdaware** [comment]
yeah right! Asking on discord will help :D

**Comment by saurabhdaware** [comment]
We can just add `<link rel="href" />` in v1 and vite will move it to top of the page. The style scoping will not work though. Might be difficult to get the scoping work with this setup so we can close this for now. Will re-open if I plan to implement it again.
