### ISSUE TITLE
Serve site over network in abell serve

### ISSUE THREAD

**Issue by saurabhdaware** [abelljs/abell#90]
**Is your feature request related to a problem? Please describe.**

Currently, the site is only served over localhost in `abell serve`.

**Describe the solution you'd like**

It should serve the site over the user's network as well.

**Additional context**

You can check out https://www.npmjs.com/package/serve. It is an NPM package to serve static HTML files. Along with serving over localhost, it also serves over local network.

**Comment by judicaelandria** [comment]
I'll take this one

**Comment by saurabhdaware** [comment]
Sure! Go ahead @judicaelandria :D

**Comment by judicaelandria** [comment]
As I here, this is only for serving an HTML file, not js server

**Comment by saurabhdaware** [comment]
It does serve js as well. Here is the code https://github.com/abelljs/abell/blob/main/src/abell-dev-server/http-server.js#L37

It's just that it serves only over `localhost` and we need a way to serve content over wifi network as well on User's IP.

**Comment by judicaelandria** [comment]
I'm talking about serve from vercel

**Comment by saurabhdaware** [comment]
Oh oh I just realized the current code already serves website over network. We just need to find the IP of the user and print it along with localhost url in `abell serve` log.

![Same content as one written below this. except without Network line](https://user-images.githubusercontent.com/30949385/96972794-965b9880-1534-11eb-9e12-d10c08a1de79.png)

So it should print,
```
Socket Server Listening...
================================================================================


💫  Abell dev server running.
Local:  http://localhost:5000 
Network: http://<user-ip-address>:5000


================================================================================
>> Watcher Connected

```

**Comment by saurabhdaware** [comment]
> I'm talking about serve from vercel

It too serves js. I don't think so we'll have to anything with it though I just showed it as an example.

**Comment by judicaelandria** [comment]
do you want me to use ipify api for that or is there another options ?

**Comment by judicaelandria** [comment]
maybe I'll leave this issue for other person for first contribution :)

**Comment by saurabhdaware** [comment]
ops I added good first issue by mistake. I meant to add dev-server label

**Comment by judicaelandria** [comment]
do you want me to use an api for that or ?

**Comment by saurabhdaware** [comment]
Node.js has a native `os` module which has information about the user's network.

Here is documentation https://nodejs.org/api/os.html#os_os_networkinterfaces

We have to find user's ipv4 address from this information and print it along with localhost.

**Comment by saurabhdaware** [comment]
Here is function from vercel's serve that finds IP address https://github.com/vercel/serve/blob/master/bin/serve.js#L171-L180

**Comment by judicaelandria** [comment]
found something like this on stack too, i'll push it now
