### ISSUE TITLE
Pluggable System for Third Party Template Engines

### ISSUE THREAD

**Issue by shadowtime2000** [abelljs/abell#96]
**Is your feature request related to a problem? Please describe.**

The `.abell` templating language may be kind of hard for users who have previously used other template engines.

**Describe the solution you'd like**

A pluggable system to allow third party template engines from `npm`.

**Additional context**

I am a maintainer of [the Eta template engine](https://github.com/eta-dev/eta) and I would like to add Abell support for `eta`.

**Comment by saurabhdaware** [comment]
Most of the features that we've built and going to build are very limited and specific about `.abell` language so maintaining a pluggable system will be difficult for Abell. I think [Eleventy](https://www.11ty.dev/) does that and it does that really well so I think that would be the right choice for this particular usecase. 

I checked out ETA though and it looks super cool! Best of luck with that project :D
